########################### Global info ############################
baseURL = 'https://jameslingford.com'
languageCode = 'en-gb'
defaultContentLanguage = "en-gb"
title = 'James Lingford'
theme = 'modified-hugo-blog'
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.
disqusShortname = 'Comments'

########################### Markup settings ############################
# set markup.highlight.noClasses=false to enable code highlight
[markup]
    [markup.highlight]
        noClasses = false
    [markup.goldmark.renderer]
        unsafe = true
        [markup.tableOfContents]
            startLevel = 2 # ToC starts from H2
            endLevel = 5 # ToC ends at H4
            ordered = false # generates <ul> instead of <ol>


########################### Banner menu ############################
[menu]
# [[menu.main]]
#     pageRef="/"
#     name = 'Home'
#     url = '/'
#     weight = 10
[[menu.main]]
    pageRef="blog"
    name = 'Blog'
    url = '/blog/'
    weight = 30
[[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 20
[[menu.main]]
    pageRef="cv"
    name = 'CV'
    url = '/cv/'
    weight = 40
[[menu.main]]
    pageRef = "contact"
    name = 'Contact'
    url = '/contact/'
    weight = 50


########################### Home page body ############################
[params]
    sitename = "James Lingford"
    defaultColor = "auto"
    mainSections = ['blog']
    toc = true
    goToTop = true
    dateFormat = "" # if nothing is specified then day-month-year format is used.
    description = "Minimal blog written by James Lingford"
    additionalScripts = ['js/custom.js', 'js/constom-2.js']
    rssFeedDescription = "summary"

[params.author]
    avatar = "james-avi3.jpg" # put the file in assets folder; also ensure that image has same height and width
    intro = "James Lingford"
    name = "James Lingford"
    description = "A personal blog about proteins and evolution. Interested in self-learning protein design, biophysics, and computational biology skills."

[params.webmanifest]
    name = "jameslingford"
    short_name = "jameslingford"
    start_url = "/"
    theme_color = "#434648"
    background_color = "#fff"
    display = "standalone"


########################### Tiles at footer ############################
# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
    TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
    name = "kofi"
    url = "https://ko-fi.com/jameslingford"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/jlingford"

[[params.socialIcons]]
    name = "twitter"
    url = "https://bsky.app/profile/dialecticbio.bsky.social"

[[params.socialIcons]]
    name = "rss"

[[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=4KSRHTUAAAAJ&hl=en"

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jameslingford/"


